# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcalorie',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='foodcalorie',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='是否逻辑删除'),
        ),
        migrations.AlterModelTable(
            name='foodcalorie',
            table='foodCalorie',
        ),
    ]
