# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0002_auto_20171030_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcalorie',
            name='content',
            field=models.CharField(max_length=500, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='foodcalorie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
    ]
